Repository GSA/usagov-benefits-eligibility, pull requests merged in 2023-05, with the labels that each got.

#770 761 update tab color
  assets/styles/theme/_uswds-theme-general.scss
  assets/styles/theme/_uswds-theme-usagov.scss
Labels: bug

#768 757 update footer styles
  assets/styles/theme/_uswds-theme-color.scss
  assets/styles/theme/_uswds-theme-usagov.scss
  components/BetaUsaGovFooter.vue
  components/BetaUsaGovFooterNav.vue
  locales/en/en.json
  mixins/FooterAccordion.js
  mixins/MatchMedia.js
Labels: bug

#778 725 update header styling
  assets/styles/theme/_uswds-theme-usagov.scss
  components/BetaUsaGovHeader.vue
Labels: bug

#806 798 miner criteria not displaying properly in retirement spanish page
  locales/es/criteria.json
Labels: V1 Maintenance Bug

#818 807 es redirect root
  middleware/middleware.js
  nuxt.config.js
  package-lock.json
  package.json
  pages/index.vue
Labels: V1 Maintenance Bug

#814 QA 813 disability es criteria
  locales/en/landing-page.json
  locales/es/criteria.json
  locales/es/es.json
  locales/es/landing-page.json
Labels: V1 Maintenance Bug

#810 797 remove unused content
  content/agencies/centers-for-medicare-and-medicaid.md
  content/agencies/department-of-defense.md
  content/agencies/fema.md
  content/agencies/social-security-administration.md
  content/agencies/u-s-department-of-education.md
  content/agencies/u-s-department-of-justice.md
  content/agencies/u-s-department-of-veteran-affairs.md
  content/life-events/becoming-a-parent.md
  content/life-events/financial-hardship.md
  content/life-events/military-service.md
  content/life-events/national-emergency-and-disaster.md
  content/life-events/school-and-education.md
  content/types/burial-and-funeral-assistance.md
  content/types/educational-assistance.md
  content/types/financial-assistance.md
  content/types/healthcare.md
  content/types/housing.md
  content/types/life-insurance.md
  content/types/training-and-jobs.md
  locales/en.js
  nuxt.config.js
  pages/agencies/_agency.vue
  pages/agencies/index.vue
  pages/types/_type.vue
  pages/types/index.vue
  test/pages/agencies/agency.spec.js
  test/pages/agencies/index.spec.js
  test/pages/types/index.spec.js
  test/pages/types/type.spec.js
Labels: V1 Maintenance Improvement

#804 801 remove single event dependecy
  layouts/default.vue
  nuxt.config.js
  pages/_lifeEvent.vue
  pages/index.vue
  test/Components/UsaGovHeader.spec.js
  test/beforeAllTests.js
  test/pages/LifeEvent.spec.js
  test/pages/LifeEvents.spec.js
Labels: V1 Maintenance Improvement

#842 Update README.md
  README.md
Labels: V1 Maintenance Improvement

#843 789 update footer styles es
  assets/styles/theme/_uswds-theme-usagov.scss
Labels: V1 Maintenance Bug

#848 847 update readme
  README.md
Labels: V1 Maintenance Improvement

#852 844 footer nav link updates
  locales/en/en.json
  locales/es/es.json
Labels: Content

#857 Maintenance Release v1.2.0
  .eslintrc.js
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/cypress.yml
  .gitignore
  README.md
  assets/styles/theme/_uswds-theme-usagov.scss
  content/benefits/ssa-supplemental-security-income-child.md
  content/benefits/ssa-supplemental-security-income-elder.md
  content/benefits/ssa-supplemental-security-income_adult.md
  cypress.config.js
  cypress/e2e/ui/header.cy.js
  cypress/support/page-objects/header.js
  locales/en/benefits/ssa-supplemental-security-income-child.json
  locales/en/benefits/ssa-supplemental-security-income-elder.json
  locales/en/benefits/ssa-supplemental-security-income_adult.json
  locales/en/en.json
  locales/es/benefits/cms-medicaid.json
  locales/es/benefits/cms-medicare-disability.json
  locales/es/benefits/dod-retirement-and-disability-payments.json
  locales/es/benefits/dod-special-compensation.json
  locales/es/benefits/doi-financial-assistance-social-services.json
  locales/es/benefits/doi-housing-improvement-program.json
  locales/es/benefits/dol-division-of-coal-mine-workers-compensation.json
  locales/es/benefits/hhs-temporary-assistance-for-needy-families.json
  locales/es/benefits/irs-tax-help-disability.json
  locales/es/benefits/irs-tax-information-retirement.json
  locales/es/benefits/nls-braille-and-audio-reading-materials.json
  locales/es/benefits/ssa-retirement-benefits-child-disabled.json
  locales/es/benefits/ssa-retirement-benefits-child.json
  locales/es/benefits/ssa-retirement-benefits-mothers-fathers.json
  locales/es/benefits/ssa-retirement-benefits-spouse.json
  locales/es/benefits/ssa-retirement-benefits.json
  locales/es/benefits/ssa-supplemental-security-income-child.json
  locales/es/benefits/ssa-supplemental-security-income-elder.json
  locales/es/benefits/ssa-supplemental-security-income_adult.json
  locales/es/benefits/ssa-ticket-to-work.json
  locales/es/benefits/va-disability-compensation.json
  locales/es/benefits/va-health-care-benefits.json
  locales/es/benefits/va-life-insurance-for-veterans.json
  locales/es/benefits/va-pension.json
  locales/es/benefits/va-program-of-comprehensive-assistance-for-family-caregivers.json
  locales/es/benefits/va-special-disability-benefits.json
  locales/es/benefits/va-veteran-readiness-and-employment.json
  locales/es/es.json
  package-lock.json
  package.json
Labels: release
