Repository GSA/usagov-benefits-eligibility, pull requests merged in 2023-06, with the labels that each got.

#893 849 poam
  package-lock.json
  package.json
Labels: V1 Maintenance Development

#904 add tests to validate opening and closing of individual accordions
  cypress/e2e/ui/accordions.cy.js
  cypress/support/page-objects/pages.js
Labels: task, javascript

#907 add test that stub print my selections
  cypress/e2e/ui/print-selections.cy.js
  cypress/support/page-objects/pages.js
Labels: javascript

#890 add links tests
  .gitignore
  cypress.config.js
  cypress/e2e/ui/links.cy.js
Labels: javascript

#909 v1.3.0 BEARS Maintenance Release
  federalist.json
  package-lock.json
  package.json
Labels: V1
